import * as materialIcons from '@material-ui/icons';
import iconTypes from '../../../constants/icon-types';

const icons = {
  [iconTypes.accessTime]: materialIcons.AccessTime,
  [iconTypes.add]: materialIcons.Add,
  [iconTypes.back]: materialIcons.ArrowBack,
  [iconTypes.business]: materialIcons.Business,
  [iconTypes.calendar]: materialIcons.CalendarToday,
  [iconTypes.close]: materialIcons.Close,
  [iconTypes.dashboard]: materialIcons.Dashboard,
  [iconTypes.dataUsage]: materialIcons.DataUsage,
  [iconTypes.delete]: materialIcons.Delete,
  [iconTypes.description]: materialIcons.Description,
  [iconTypes.download]: materialIcons.SaveAlt,
  [iconTypes.edit]: materialIcons.Edit,
  [iconTypes.events]: materialIcons.Event,
  [iconTypes.exit]: materialIcons.MeetingRoomOutlined,
  [iconTypes.filter]: materialIcons.FilterList,
  [iconTypes.login]: materialIcons.MeetingRoom,
  [iconTypes.home]: materialIcons.Home,
  [iconTypes.left]: materialIcons.KeyboardArrowLeft,
  [iconTypes.list]: materialIcons.ViewList,
  [iconTypes.location]: materialIcons.LocationOn,
  [iconTypes.logout]: materialIcons.ExitToApp,
  [iconTypes.menu]: materialIcons.Menu,
  [iconTypes.more]: materialIcons.MoreHoriz,
  [iconTypes.people]: materialIcons.People,
  [iconTypes.person]: materialIcons.Person,
  [iconTypes.personAdd]: materialIcons.PersonAdd,
  [iconTypes.personAddDisabled]: materialIcons.PersonAddDisabled,
  [iconTypes.search]: materialIcons.Search,
  [iconTypes.setDark]: materialIcons.Brightness4,
  [iconTypes.setLight]: materialIcons.BrightnessHigh,
  [iconTypes.settings]: materialIcons.Settings,
  [iconTypes.sort]: materialIcons.Sort,
  [iconTypes.stats]: materialIcons.Equalizer,
  [iconTypes.supervisedUser]: materialIcons.SupervisedUserCircle,
  [iconTypes.upload]: materialIcons.Publish,
  [iconTypes.uploadCloud]: materialIcons.CloudUpload,
};

export default icons;
