const iconTypes = {
  accessTime: 'accessTime',
  add: 'add',
  back: 'back',
  business: 'business',
  calendar: 'calendar',
  close: 'close',
  dashboard: 'dashboard',
  dataUsage: 'dataUsage',
  delete: 'delete',
  description: 'description',
  download: 'download',
  edit: 'edit',
  events: 'events',
  exit: 'exit',
  filter: 'filter',
  login: 'login',
  home: 'home',
  left: 'left',
  list: 'list',
  location: 'location',
  logout: 'logout',
  menu: 'menu',
  more: 'more',
  people: 'people',
  person: 'person',
  personAdd: 'personAdd',
  personAddDisabled: 'personAddDisabled',
  search: 'search',
  setDark: 'setDark',
  setLight: 'setLight',
  settings: 'settings',
  sort: 'sort',
  stats: 'stats',
  supervisedUser: 'supervisedUser',
  upload: 'upload',
  uploadCloud: 'uploadCloud',
};

export default iconTypes;
