const images = {
  basic_file: '/public/svg/file.svg',
  bpm: '/public/svg/bmp.svg',
  doc: '/public/svg/doc.svg',
  docx: '/public/svg/docx.svg',
  eventDefault: '/public/svg/event-default.svg',
  eventDefaultDark: '/public/svg/event-default-dark.svg',
  favicon: '/public/svg/favicon.svg',
  folder: '/public/svg/folder.svg',
  gif: '/public/svg/gif.svg',
  home: '/public/svg/home.svg',
  homeDark: '/public/svg/home-dark.svg',
  jpg: '/public/svg/jpg.svg',
  logoLight: '/public/svg/logo_light.svg',
  logoDark: '/public/svg/logo_dark.svg',
  pattern: '/public/svg/pattern.svg',
  pdf: '/public/svg/pdf.svg',
  png: '/public/svg/png.svg',
  ppt: '/public/svg/ppt.svg',
  pptx: '/public/svg/pptx.svg',
  svg: '/public/svg/svg.svg',
  xls: '/public/svg/xls.svg',
  xlsx: '/public/svg/xlsx.svg',
  zip: '/public/svg/zip.svg',
};

export default images;
