version: "${DOCKER_COMPOSE_VERSION}"

services:
  client:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: matheventclient
    container_name: matheventclient
    platform: "${DOCKER_COMPOSE_IMAGE_PLATFORM}"
    networks:
      - mathevent
    ports:
      - 443:443
    volumes:
      - ./nginx/certs/${CERT_NAME}.crt:/etc/ssl/certs/cert.crt
      - ./nginx/certs/${KEY_NAME}.key:/etc/ssl/private/cert-key.key
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  mathevent:
    external: true